import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1.5rem", screens: { "2xl": "1400px" } },
    screens: {
      xs: "400px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: {
        display: ["'Space Grotesk'", "Inter", "sans-serif"],
        wordmark: ["'Cinzel Decorative'", "'Space Grotesk'", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        quiz: {
          correct: "hsl(var(--quiz-correct))",
          "correct-surface": "hsl(var(--quiz-correct-surface))",
          incorrect: "hsl(var(--quiz-incorrect))",
          "incorrect-surface": "hsl(var(--quiz-incorrect-surface))",
        },
        portal: {
          reveal: "hsl(var(--portal-reveal))",
        },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        gold: { DEFAULT: "hsl(var(--gold))", foreground: "hsl(var(--gold-foreground))" },
        cyan: { DEFAULT: "hsl(var(--cyan))", foreground: "hsl(var(--cyan-foreground))" },
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-violet': 'var(--gradient-violet)',
        'gradient-cyan': 'var(--gradient-cyan)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-gold': 'var(--gradient-gold)',
        'gradient-hero': 'var(--gradient-hero)',
      },
      boxShadow: {
        glow: 'var(--shadow-glow)',
        'glow-strong': 'var(--shadow-glow-strong)',
        gold: 'var(--shadow-gold)',
        violet: 'var(--shadow-violet)',
        soft: 'var(--shadow-soft)',
        card: 'var(--shadow-card)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in-up": { "0%": { opacity: "0", transform: "translateY(40px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.9)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "float": { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-15px)" } },
        "float-slow": { "0%,100%": { transform: "translateY(0) rotate(0deg)" }, "50%": { transform: "translateY(-20px) rotate(5deg)" } },
        
        "glow-pulse": { "0%,100%": { boxShadow: "0 0 20px hsl(var(--primary) / 0.4)" }, "50%": { boxShadow: "0 0 40px hsl(var(--primary) / 0.8)" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "progress-fill": { "0%": { width: "0%" }, "100%": { width: "var(--progress, 75%)" } },
        "spin-slow": { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        "spotlight-sway": { "0%,100%": { transform: "translateX(-3%) rotate(-2deg)", opacity: "0.85" }, "50%": { transform: "translateX(3%) rotate(2deg)", opacity: "1" } },
        "tier-rise": { "0%": { opacity: "0", transform: "translateX(-20px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "fade-in-only": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "quiz-bg-fade": { "0%": { opacity: "0" }, "100%": { opacity: "0.7" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out forwards",
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        "fade-in-only": "fade-in-only 0.5s ease-out forwards",
        "quiz-bg-fade": "quiz-bg-fade 0.9s ease-out forwards",
        "scale-in": "scale-in 0.5s ease-out forwards",
        "float": "float 4s ease-in-out infinite",
        "float-slow": "float-slow 6s ease-in-out infinite",
        
        "glow-pulse": "glow-pulse 2.5s ease-in-out infinite",
        "shimmer": "shimmer 3s linear infinite",
        "progress-fill": "progress-fill 1.5s cubic-bezier(0.4,0,0.2,1) forwards",
        "spin-slow": "spin-slow 12s linear infinite",
        "spotlight-sway": "spotlight-sway 6s ease-in-out infinite",
        "tier-rise": "tier-rise 0.5s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
